name: Deploy FTP

on:
    push:
        branches:
            - main

jobs:
    ftp-deploy:
        name: Deploy to FTP
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: FTP Upload
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  port: ${{ secrets.FTP_PORT }}
                  protocol: ${{ secrets.FTP_PROTOCOL }}
                  local-dir: ./
                  server-dir: ${{ secrets.FTP_DIR }}
